"use client";
import { FormEvent, useState } from "react";

const cases={
  "câncer de mama":{claim:"Desodorante antitranspirante causa câncer de mama",origin:"Publicação simulada em rede social",date:"12 jul. 2026",assessment:"Evidência disponível não sustenta relação causal",confidence:"Moderada",why:"Os estudos observacionais de exemplo não identificaram associação consistente. Isso não prova ausência absoluta de risco, mas contrasta com a certeza da alegação.",articles:[{title:"Antiperspirant use and breast cancer risk: a review",year:"2024",method:"Revisão narrativa demonstrativa",authors:"M. Costa; J. Lee",signal:"não sustenta"},{title:"Lifestyle exposures in breast cancer epidemiology",year:"2023",method:"Coorte demonstrativa",authors:"A. Kumar et al.",signal:"inconclusivo"}],pitch:"Por que mitos sobre cosméticos e câncer persistem mesmo sem evidência causal robusta? A pauta pode investigar a origem da alegação, o grau de certeza permitido pelos estudos e como especialistas comunicam risco.",researchers:[{name:"Marina Alves",inst:"Universidade Exemplo do Sudeste",area:"Epidemiologia do câncer",score:92,reason:"5 publicações demonstrativas recentes e aderência direta ao tema"},{name:"Paulo Nunes",inst:"Instituto Nacional Fictício de Saúde",area:"Comunicação de risco",score:84,reason:"Pesquisa desinformação em saúde; vínculo ilustrativo"}]},
  "curas naturais":{claim:"Uma dieta alcalina elimina tumores sem tratamento médico",origin:"Blog de bem-estar simulado",date:"3 jun. 2026",assessment:"Alegação contradiz o conjunto demonstrativo de evidências",confidence:"Alta",why:"Os registros de exemplo não mostram eficácia clínica da dieta como tratamento e apontam risco em substituir terapias indicadas.",articles:[{title:"Dietary patterns and cancer treatment outcomes",year:"2025",method:"Revisão sistemática demonstrativa",authors:"L. Martins et al.",signal:"contradiz"},{title:"Nutrition as supportive care in oncology",year:"2024",method:"Ensaio clínico demonstrativo",authors:"R. Chen; D. Souza",signal:"não sustenta"}],pitch:"Como promessas de cura alimentar transformam cuidado de suporte em substituto indevido de tratamento? Ouvir oncologistas e nutricionistas sobre limites da evidência.",researchers:[{name:"Luciana Prado",inst:"Universidade Pública Demonstrativa",area:"Nutrição oncológica",score:90,reason:"Aderência temática e produção recente no lote de exemplo"},{name:"Rafael Sato",inst:"Centro Fictício de Oncologia",area:"Ensaios clínicos",score:79,reason:"Métodos pertinentes; vínculo ainda precisaria ser confirmado"}]}
};
type Topic=keyof typeof cases;
export default function Home(){const [query,setQuery]=useState("câncer de mama");const [topic,setTopic]=useState<Topic>("câncer de mama");const [tab,setTab]=useState<"analysis"|"science"|"sources">("analysis");const [loading,setLoading]=useState(false);const [custom,setCustom]=useState("");const data=cases[topic];function submit(e:FormEvent){e.preventDefault();setLoading(true);setTimeout(()=>{const q=query.toLowerCase();setTopic(q.includes("dieta")||q.includes("natural")?"curas naturais":"câncer de mama");setCustom(Object.keys(cases).some(k=>q.includes(k))?"":"A busca foi aproximada ao caso demonstrativo mais próximo. A cobertura real ainda não está conectada.");setLoading(false);},700)}return <main>
  <div className="demo"><b>DEMONSTRAÇÃO</b><span>Alegações, artigos e pesquisadores abaixo são fictícios e servem apenas para testar o fluxo.</span></div>
  <header><a href="#" className="brand"><span>∆</span>Evidência em pauta</a><nav>Grupo 2 · Oficina Codesinfo</nav></header>
  <section className="hero"><div><p className="eyebrow">APOIO À APURAÇÃO EM SAÚDE</p><h1>Da alegação à<br/><em>pergunta jornalística.</em></h1><p>Organize sinais de desinformação, literatura científica e fontes possíveis — sem terceirizar a conclusão editorial.</p></div><form onSubmit={submit}><label htmlFor="search">O que você quer investigar?</label><div><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: câncer de mama"/><button disabled={loading}>{loading?"Buscando…":"Analisar →"}</button></div><small>Experimente “câncer de mama” ou “curas naturais”.</small></form></section>
  {custom&&<div className="notice">{custom}</div>}
  <section className="case-head"><div><p className="eyebrow">CASO DEMONSTRATIVO SELECIONADO</p><h2>{data.claim}</h2><p>{data.origin} · {data.date} · URL propositalmente omitida por ser um exemplo fictício</p></div><span className="simulation-stamp">CONTEÚDO SIMULADO</span></section>
  <div className="tabs"><button className={tab==="analysis"?"active":""} onClick={()=>setTab("analysis")}>Leitura da alegação</button><button className={tab==="science"?"active":""} onClick={()=>setTab("science")}>Evidências científicas <i>{data.articles.length}</i></button><button className={tab==="sources"?"active":""} onClick={()=>setTab("sources")}>Fontes para a pauta <i>{data.researchers.length}</i></button></div>
  <section className="workspace">
    {tab==="analysis"&&<><div className="verdict"><div className="status-icon">≈</div><div><p className="eyebrow">SINAL DA ANÁLISE</p><h2>{data.assessment}</h2><p>{data.why}</p></div><div className="confidence"><small>Confiança</small><b>{data.confidence}</b><span>do cenário simulado</span></div></div><div className="analysis-grid"><article><span>01</span><h3>O que a alegação afirma</h3><blockquote>“{data.claim}”</blockquote><p>Formulação absoluta e causal, apresentada sem método ou grau de incerteza.</p></article><article><span>02</span><h3>O que procurar na evidência</h3><ul><li>Desenho e tamanho dos estudos</li><li>Diferença entre associação e causalidade</li><li>Consistência entre resultados</li><li>Limitações declaradas pelos autores</li></ul></article></div><div className="pitch"><p className="eyebrow">SUGESTÃO DE PAUTA</p><h2>{data.pitch}</h2><small>Gerada apenas a partir do conjunto demonstrativo exibido nesta página.</small></div></>}
    {tab==="science"&&<div className="science"><div className="section-intro"><p className="eyebrow">PUBMED · RESULTADOS SIMULADOS</p><h2>Literatura relacionada</h2><p>Metadados inventados para demonstrar organização. Nenhum link é apresentado como registro real.</p></div>{data.articles.map((a,i)=><article key={a.title}><span>{String(i+1).padStart(2,"0")}</span><div><b>{a.signal}</b><h3>{a.title}</h3><p>{a.authors} · {a.year}</p><small>{a.method}</small></div><button title="Indisponível no protótipo">Ver registro simulado ↗</button></article>)}</div>}
    {tab==="sources"&&<div className="sources"><div className="section-intro"><p className="eyebrow">PESQUISADORES · LOTE SIMULADO</p><h2>Possíveis fontes</h2><p>Os nomes e vínculos são fictícios. O ranking explica aderência, não autoridade absoluta.</p></div>{data.researchers.map((r,i)=><article key={r.name}><div className="rank">{i+1}</div><div><h3>{r.name}</h3><p>{r.area} · {r.inst}</p><small>{r.reason}</small></div><div className="score"><b>{r.score}</b><span>aderência demonstrativa</span></div></article>)}</div>}
  </section>
  <aside className="limits"><b>Como ler este protótipo</b><p>Ele não diagnostica, não aconselha tratamento e não classifica automaticamente uma afirmação como verdadeira ou falsa. Na versão real, toda alegação terá URL rastreável e todo artigo virá do PubMed.</p></aside>
  <footer><span>Evidência em pauta · demonstração funcional</span><span>Conclusão editorial sempre humana</span></footer>
  </main>}
