"use client";
import { FormEvent, useState } from "react";

const cases={
  "câncer de mama":{claim:"Desodorante antitranspirante causa câncer de mama",origin:"Alegação criada para demonstrar o fluxo",date:"sem data ou URL",assessment:"Os registros selecionados contradizem a alegação",confidence:"Provisória",why:"Uma meta-análise de sete estudos caso-controle e um estudo populacional não encontraram associação. A meta-análise ressalta que estudos prospectivos ainda são necessários; isso impede tratar o resultado como prova de risco absolutamente zero.",articles:[{title:"Use of Antiperspirant Products and Risk of Breast Cancer: A Meta-Analysis of Case-Control Studies",year:"2024",method:"Meta-análise de 7 estudos caso-controle · PMID 39324502",authors:"Trinh TTK; Myung SK; Tran TH; Choi KS",signal:"contradiz",url:"https://pubmed.ncbi.nlm.nih.gov/39324502/"},{title:"Antiperspirant use and the risk of breast cancer",year:"2002",method:"Estudo caso-controle populacional: 813 casos e 793 controles · PMID 12381712",authors:"Mirick DK; Davis S; Thomas DB",signal:"contradiz",url:"https://pubmed.ncbi.nlm.nih.gov/12381712/"}],pitch:"Por que o boato sobre desodorantes e câncer de mama persiste após décadas de estudos sem associação? A pauta pode explicar o que estudos caso-controle conseguem — e não conseguem — demonstrar e por que ausência de associação não é prova de risco zero.",researchers:[{name:"Thao Thi Kim Trinh",inst:"National Cancer Center Graduate School of Cancer Science and Policy, Coreia do Sul",area:"Controle populacional do câncer",score:92,reason:"Primeira autora da meta-análise mais recente selecionada; vínculo informado pelo PubMed e aderência direta ao tema."},{name:"Seung-Kwon Myung",inst:"National Cancer Center, Coreia do Sul",area:"Epidemiologia e prevenção",score:86,reason:"Coautor da meta-análise selecionada. A pontuação demonstra pertinência, não autoridade definitiva."}]},
  "curas naturais":{claim:"Cortar todo o açúcar impede um tumor de crescer",origin:"Alegação criada para demonstrar o fluxo",date:"sem data ou URL",assessment:"A alegação simplifica uma evidência inconclusiva",confidence:"Provisória",why:"A literatura distingue consumo de açúcar, adiposidade, risco de câncer e tratamento. Os registros selecionados não sustentam a promessa de que eliminar açúcar interrompa um tumor.",articles:[{title:"Consumption of Sugars, Sugary Foods, and Sugary Beverages in Relation to Cancer Risk",year:"2018",method:"Revisão sistemática de 37 coortes prospectivas · PMID 29801420",authors:"Makarem N; Bandera EV; Nicholson JM; Parekh N",signal:"inconclusivo",url:"https://pubmed.ncbi.nlm.nih.gov/29801420/"},{title:"Dietary sugar consumption and health: umbrella review",year:"2023",method:"Revisão guarda-chuva de 73 meta-análises · PMID 37019448",authors:"Huang Y et al.",signal:"não sustenta a promessa",url:"https://pubmed.ncbi.nlm.nih.gov/37019448/"}],pitch:"Da recomendação nutricional à falsa promessa terapêutica: como conteúdos online transformam associações entre dieta e risco em uma suposta cura do câncer? Separar prevenção, metabolismo e tratamento.",researchers:[{name:"Nour Makarem",inst:"Columbia University Medical Center (vínculo no registro de 2018)",area:"Nutrição e epidemiologia",score:90,reason:"Primeira autora da revisão sistemática selecionada; vínculo atual deve ser confirmado pela redação."},{name:"Niyati Parekh",inst:"NYU School of Global Public Health (vínculo no registro de 2018)",area:"Saúde populacional",score:81,reason:"Coautora da revisão selecionada. A lista não representa um censo de especialistas."}]}
};
type Topic=keyof typeof cases;
export default function Home(){const [query,setQuery]=useState("câncer de mama");const [topic,setTopic]=useState<Topic>("câncer de mama");const [tab,setTab]=useState<"analysis"|"science"|"sources">("analysis");const [loading,setLoading]=useState(false);const [custom,setCustom]=useState("");const data=cases[topic];function submit(e:FormEvent){e.preventDefault();setLoading(true);setTimeout(()=>{const q=query.toLowerCase();setTopic(q.includes("dieta")||q.includes("natural")?"curas naturais":"câncer de mama");setCustom(Object.keys(cases).some(k=>q.includes(k))?"":"A busca foi aproximada ao caso demonstrativo mais próximo. A cobertura real ainda não está conectada.");setLoading(false);},700)}return <main>
  <div className="demo"><b>DEMONSTRAÇÃO</b><span>Alegações são exemplos sem origem real. Artigos, links e autorias vêm de registros públicos verificáveis do PubMed.</span></div>
  <header><a href="#" className="brand"><span>∆</span>Evidência em pauta</a><nav>Grupo 2 · Oficina Codesinfo</nav></header>
  <section className="hero"><div><p className="eyebrow">APOIO À APURAÇÃO EM SAÚDE</p><h1>Da alegação à<br/><em>pergunta jornalística.</em></h1><p>Organize sinais de desinformação, literatura científica e fontes possíveis — sem terceirizar a conclusão editorial.</p></div><form onSubmit={submit}><label htmlFor="search">Escolha um tema ou cole uma alegação</label><div><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: desodorante causa câncer de mama" required minLength={4}/><button disabled={loading}>{loading?"Consultando demonstração…":"Analisar →"}</button></div><small>Experimente “câncer de mama”, “açúcar” ou “curas naturais”. O texto não é enviado nem armazenado.</small></form></section>
  {custom&&<div className="notice">{custom}</div>}
  <section className="case-head"><div><p className="eyebrow">ALEGAÇÃO DEMONSTRATIVA SELECIONADA</p><h2>{data.claim}</h2><p>{data.origin} · {data.date} · ausência de origem é dado ausente, não evidência negativa</p></div><span className="simulation-stamp">ALEGAÇÃO SIMULADA</span></section>
  <div className="tabs"><button className={tab==="analysis"?"active":""} onClick={()=>setTab("analysis")}>Leitura da alegação</button><button className={tab==="science"?"active":""} onClick={()=>setTab("science")}>Evidências científicas <i>{data.articles.length}</i></button><button className={tab==="sources"?"active":""} onClick={()=>setTab("sources")}>Fontes para a pauta <i>{data.researchers.length}</i></button></div>
  <section className="workspace">
    {tab==="analysis"&&<><div className="verdict"><div className="status-icon">≈</div><div><p className="eyebrow">SINAL DA ANÁLISE</p><h2>{data.assessment}</h2><p>{data.why}</p></div><div className="confidence"><small>Confiança</small><b>{data.confidence}</b><span>do cenário simulado</span></div></div><div className="analysis-grid"><article><span>01</span><h3>O que a alegação afirma</h3><blockquote>“{data.claim}”</blockquote><p>Formulação absoluta e causal, apresentada sem método ou grau de incerteza.</p></article><article><span>02</span><h3>O que procurar na evidência</h3><ul><li>Desenho e tamanho dos estudos</li><li>Diferença entre associação e causalidade</li><li>Consistência entre resultados</li><li>Limitações declaradas pelos autores</li></ul></article></div><div className="pitch"><p className="eyebrow">SUGESTÃO DE PAUTA</p><h2>{data.pitch}</h2><small>Gerada apenas a partir do conjunto demonstrativo exibido nesta página.</small></div></>}
    {tab==="science"&&<div className="science"><div className="section-intro"><p className="eyebrow">PUBMED · AMOSTRA VERIFICÁVEL</p><h2>Literatura relacionada</h2><p>Dois registros reais foram selecionados para testar o fluxo. A amostra não equivale a uma revisão completa.</p></div>{data.articles.map((a,i)=><article key={a.title}><span>{String(i+1).padStart(2,"0")}</span><div><b>{a.signal}</b><h3>{a.title}</h3><p>{a.authors} · {a.year}</p><small>{a.method}</small></div><a href={a.url} target="_blank" rel="noreferrer">Abrir no PubMed ↗</a></article>)}</div>}
    {tab==="sources"&&<div className="sources"><div className="section-intro"><p className="eyebrow">AUTORES DOS REGISTROS SELECIONADOS</p><h2>Possíveis fontes</h2><p>Nomes e vínculos derivam do PubMed; identidade, vínculo atual e disponibilidade exigem confirmação editorial.</p></div>{data.researchers.map((r,i)=><article key={r.name}><div className="rank">{i+1}</div><div><h3>{r.name}</h3><p>{r.area} · {r.inst}</p><small>{r.reason}</small></div><div className="score"><b>{r.score}</b><span>aderência demonstrativa</span></div></article>)}</div>}
  </section>
  <aside className="limits"><b>Como ler este protótipo</b><p>Ele não diagnostica, não aconselha tratamento e não classifica automaticamente uma afirmação como verdadeira ou falsa. A busca não varre a internet: as alegações são simuladas e os dois artigos de cada cenário são uma amostra verificável do PubMed. Sexo, gênero e outros atributos sensíveis não são inferidos.</p></aside>
  <footer><span>Evidência em pauta · demonstração funcional</span><span>Conclusão editorial sempre humana</span></footer>
  </main>}
